name: ai-weiquan

services:
  legal-assistant:
    build: .
    image: ai-weiquan:v0.1.0
    platform: linux/amd64
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=sk-7qiEVTkcmI2Lq5O8hVEXgtdiuBzwZvFcYLszs3UKcfVdGU75
      - BASE_URL=http://192.168.0.151:3001/v1
      - MODEL_NAME=kj-qwen3-max
    restart: unless-stopped