name: legal-assistant-project

services:
  legal-assistant:
    build: .
    image: legal-assistant:v0.1.0
    platform: linux/amd64
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=sk-71FSn965RKqZp04B610f53069aBe4fB7Bc3799Bf60F0B99e
      - OPENAI_API_BASE=http://oneapi-dev.skytech.io/v1
      - OPENAI_MODEL_NAME=gpt-4o
    restart: unless-stopped